version: '3'

networks:
  jenkins:
    driver: bridge

services:
  # Docker-In-Docker service
  dind:
    image: docker:latest
    container_name: dind
    privileged: true
    networks:
      - jenkins
    command: >
      --network jenkins
      --network-alias docker
      -u root
      -e DOCKER_TLS_CERTDIR=/certs
      -v docker-certs-ca:/certs/ca
      -v docker-certs-client:/certs/client
      -v jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:
